project:
  name: "DFBS Object Classification"
  root: "/home/sargis/Datasets/Stepan/DFBS_Classification"
  train_id: "Default_10_AdaDelta"
model:
  load_path: # f'{checkpoints_dir}/100.pth'
training:
  use_gpu: True
  batch_size:
    train: 256
    test: 128
    val: 1
  epochs: 301
  start_epoch: 0
data:
  input:
    shape: [160, 50]
  output:
    num_classes: 10
  train:
    path: '/home/sargis/Datasets/Stepan/DFBS_Combine/train'
  test:
    path: '/home/sargis/Datasets/Stepan/DFBS_Combine/test'
  val:
    path: